# Generated by Django 3.2.15 on 2022-09-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='Film İsmi')),
                ('resim', models.FileField(upload_to='filmler/', verbose_name='Film Resmi')),
            ],
        ),
    ]
